package:
  name: r-rlandsat8
  version: 0.1

source:
  path: ../src

requirements:
  build:
    - r=3.3.2
    - r-raster
    - r-rcurl

  run:
    - r=3.3.2
    - r-raster
    - r-rcurl
    
test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rLandsat8')"   
      